### ISSUE TITLE
Addition of other pipelines

### ISSUE THREAD

**Issue by ghost** [c-w/opener-docker-language-identifier#1]
Would it be possible to add other pipelines in as well? Such as the sentiment analysis?

**Comment by c-w** [comment]
Hi @DEVKWS, thanks for reaching out.

For now, there are docker-images/services for the following NLP tasks: [Language Identification](https://github.com/c-w/opener-docker-language-identifier), [Tokenization](https://github.com/c-w/opener-docker-tokenizer), [Part of Speech Tagging](https://github.com/c-w/opener-docker-pos-tagger) and [Named Entity Recognition](https://github.com/c-w/opener-docker-ner). There also is a docker-image/service for a [wrapper](https://github.com/c-w/opener-docker-wrapper) to make consuming the pipeline easier.

I haven't implemented OpeNER's polarity tagging because so far I've been pretty happy with [Azure Text Analytics](https://docs.microsoft.com/en-us/azure/cognitive-services/text-analytics/how-tos/text-analytics-how-to-sentiment-analysis) which currently supports [15 languages](https://docs.microsoft.com/en-us/azure/cognitive-services/text-analytics/text-analytics-supported-languages), so it's even more widely usable than OpeNER's implementation.

However, if you follow the model outlined in the repositories linked in this comment, it should be pretty easy to extend the work to also include the polarity tagging. If you implement this, please let me know and I'll link to your work from these repositories.

**Comment by ghost** [comment]
Thank you for the prompt and informative reply. We wanted to avoid further Azure costs associated with cognitive services, and full French support is a requirement for us. I will invest some time and add in the remaining pipelines of OpeNER. I will let you know when it’s complete. 

Side note: Your article on Microsoft.com about this project is excellent.

**Comment by c-w** [comment]
Glad you enjoyed the article :) Let me know how the implementation of the polarity tagger goes and feel free to reach out if you have any questions.
